[package]
name = "domain_list_builder"
version = "0.1.0"
authors = ["Alex Williams <hughaw64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockconvert = "^0.4.3"

reqwest = {version = "0.11", features = ["rustls-tls", "json"]}
futures = {version = "0.3"}
tokio = {version = "1.2", features = ["macros", "rt", "rt-multi-thread", "fs", "io-util", "time", "net", "sync"]}
tokio-stream = {version = "0.1", features = ["fs"]}
rand = "0.8"
serde = {version = "1.0", features = ["derive"]}
lazy_static = "1.4"
tokio-tungstenite = {version = "0.13", features = ["tls"]}

csv = "1.1"
serde_json = "1.0"

regex = {version = "1.4", features = ["std", "perf"]}

chrono = "0.4"
filetime = "0.2"

clap = "3.0.0-beta.2"

parking_lot = "0.11"

[profile.release]
debug = true